name: NIP Rent

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    name: Test and Deploy
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install UV
      uses: astral-sh/setup-uv@v5

    - name: Install project
      run: uv sync --dev

    - name: Run tests
      run: uv run pytest tests -v || true  # Kontynuuj nawet jeśli testy padną

    - name: Run linter
      run: uv run ruff check src --exit-zero # Sprawdź błędy, ale nie przerywaj

    - name: Generate Docs
      run: uvx pdoc src/ -o ./docs-output

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs-output'

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4